M48
; DRILL file {KiCad (6.0.4-0)} date Wednesday, 25 May 2022 at 01.46.19
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-05-25T01:46:19+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0512
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0630
%
G90
G05
T1
X5.3456Y-4.3996
X5.3465Y-4.2028
T2
X11.0689Y-4.2488
T0
M30
